# Spectral OpenAPI Linter Configuration
# See: https://docs.stoplight.io/docs/spectral/

extends:
  - "spectral:oas"

# Custom rule severity overrides
rules:
  # Ensure all operations have unique operationId (critical for SDK generation)
  operation-operationId-unique: error
  # Ensure all operations have descriptions (important for documentation)
  operation-description: warn
  # Ensure all operations have operationId (critical for SDK generation)
  operation-operationId: warn
